config/routes.rb
Skeletor::Application.routes.draw do
  
  resources :projects do
    resource :grid
    resources :layouts, :libraries, :pages
  end
    

  
  root :to => "projects#index"

end

app/models/grid.rb
class Grid < ActiveRecord::Base
  attr_accessible :columns, :width, :gutter_width
  
  belongs_to :project
end

app/models/layout.rb
class Layout < ActiveRecord::Base
  attr_accessible :name
  
  belongs_to :project
end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :name
  
  belongs_to :project
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :name, :markup, :styles
  
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :overview, :announcement, :status
  
  has_one :grid, :dependent => :destroy
  has_many :layouts, :dependent => :destroy
  has_many :libraries
  has_many :pages, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  def index
    @grids = Grid.all
  end

  def show
    @grid = Grid.find(params[:id])
  end

  def new
    @grid = Grid.new
  end

  def create
    @grid = Grid.new(params[:grid])
    if @grid.save
      redirect_to @grid, :notice => "Successfully created grid."
    else
      render :action => 'new'
    end
  end

  def edit
    @grid = Grid.find(params[:id])
  end

  def update
    @grid = Grid.find(params[:id])
    if @grid.update_attributes(params[:grid])
      redirect_to @grid, :notice  => "Successfully updated grid."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @grid = Grid.find(params[:id])
    @grid.destroy
    redirect_to grids_url, :notice => "Successfully destroyed grid."
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def index
    @layouts = Layout.all
  end

  def show
    @layout = Layout.find(params[:id])
  end

  def new
    @layout = Layout.new
  end

  def create
    @layout = Layout.new(params[:layout])
    if @layout.save
      redirect_to @layout, :notice => "Successfully created layout."
    else
      render :action => 'new'
    end
  end

  def edit
    @layout = Layout.find(params[:id])
  end

  def update
    @layout = Layout.find(params[:id])
    if @layout.update_attributes(params[:layout])
      redirect_to @layout, :notice  => "Successfully updated layout."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @layout = Layout.find(params[:id])
    @layout.destroy
    redirect_to layouts_url, :notice => "Successfully destroyed layout."
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def show
    @library = Library.find(params[:id])
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.new(params[:library])
    if @library.save
      redirect_to @library, :notice => "Successfully created library."
    else
      render :action => 'new'
    end
  end

  def edit
    @library = Library.find(params[:id])
  end

  def update
    @library = Library.find(params[:id])
    if @library.update_attributes(params[:library])
      redirect_to @library, :notice  => "Successfully updated library."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @library = Library.find(params[:id])
    @library.destroy
    redirect_to libraries_url, :notice => "Successfully destroyed library."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to @page, :notice => "Successfully created page."
    else
      render :action => 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to @page, :notice  => "Successfully updated page."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to pages_url, :notice => "Successfully destroyed page."
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, :notice => "Successfully created project."
    else
      render :action => 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice  => "Successfully updated project."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url, :notice => "Successfully destroyed project."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
module LayoutHelper

  def body_class
    @body_class ||= "#{controller.controller_name} #{controller.action_name}"
  end
  
  def title
    @title ||= 'skeletor'
  end
    
  def flash_messages
    capture_haml do
      haml_tag :div, :id => 'flash' do
        %w(notice alert).each do |msg|
          haml_tag :div, flash[msg.to_sym], :class => msg unless flash[msg.to_sym].blank?
        end
      end
    end
  end
  
end

app/helpers/path_helper.rb
module PathHelper
  def void_path
    "javascript:void(0)"    
  end
end

app/views/grids/_form.html.erb
<%= form_for @grid do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </p>
  <p>
    <%= f.label :columns %><br />
    <%= f.text_field :columns %>
  </p>
  <p>
    <%= f.label :width %><br />
    <%= f.text_field :width %>
  </p>
  <p>
    <%= f.label :gutter_width %><br />
    <%= f.text_field :gutter_width %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/grids/edit.html.erb
<% title "Edit Grid" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @grid %> |
  <%= link_to "View All", grids_path %>
</p>

app/views/grids/index.html.erb
<% title "Grids" %>

<table>
  <tr>
    <th>Project</th>
    <th>Columns</th>
    <th>Width</th>
    <th>Gutter Width</th>
  </tr>
  <% for grid in @grids %>
    <tr>
      <td><%= grid.project_id %></td>
      <td><%= grid.columns %></td>
      <td><%= grid.width %></td>
      <td><%= grid.gutter_width %></td>
      <td><%= link_to "Show", grid %></td>
      <td><%= link_to "Edit", edit_grid_path(grid) %></td>
      <td><%= link_to "Destroy", grid, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Grid", new_grid_path %></p>

app/views/grids/new.html.erb
<% title "New Grid" %>

<%= render 'form' %>

<p><%= link_to "Back to List", grids_path %></p>

app/views/grids/show.html.erb
<% title "Grid" %>

<p>
  <strong>Project:</strong>
  <%= @grid.project_id %>
</p>
<p>
  <strong>Columns:</strong>
  <%= @grid.columns %>
</p>
<p>
  <strong>Width:</strong>
  <%= @grid.width %>
</p>
<p>
  <strong>Gutter Width:</strong>
  <%= @grid.gutter_width %>
</p>

<p>
  <%= link_to "Edit", edit_grid_path(@grid) %> |
  <%= link_to "Destroy", @grid, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", grids_path %>
</p>

app/views/layouts/_form.html.erb
<%= form_for @layout do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/_header.html.haml
%header
  %h1.site
    = link_to 'sk', projects_path
  %nav
    = link_to 'account', void_path

= flash_messages

= content_for :title

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= title
    = stylesheet_link_tag 'application'
    = csrf_meta_tag

  %body{:class => body_class}
    #body
      = render 'layouts/header'
      #content
        = yield

      = content_for :modal
    = javascript_include_tag 'application'

app/views/layouts/edit.html.erb
<% title "Edit Layout" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @layout %> |
  <%= link_to "View All", layouts_path %>
</p>

app/views/layouts/index.html.erb
<% title "Layouts" %>

<table>
  <tr>
    <th>Project</th>
    <th>Name</th>
  </tr>
  <% for layout in @layouts %>
    <tr>
      <td><%= layout.project_id %></td>
      <td><%= layout.name %></td>
      <td><%= link_to "Show", layout %></td>
      <td><%= link_to "Edit", edit_layout_path(layout) %></td>
      <td><%= link_to "Destroy", layout, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Layout", new_layout_path %></p>

app/views/layouts/new.html.erb
<% title "New Layout" %>

<%= render 'form' %>

<p><%= link_to "Back to List", layouts_path %></p>

app/views/layouts/show.html.erb
<% title "Layout" %>

<p>
  <strong>Project:</strong>
  <%= @layout.project_id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @layout.name %>
</p>

<p>
  <%= link_to "Edit", edit_layout_path(@layout) %> |
  <%= link_to "Destroy", @layout, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", layouts_path %>
</p>

app/views/libraries/_form.html.erb
<%= form_for @library do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </p>
  <p>
    <%= f.label :account_id %><br />
    <%= f.text_field :account_id %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :global %><br />
    <%= f.check_box :global %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/libraries/edit.html.erb
<% title "Edit Library" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @library %> |
  <%= link_to "View All", libraries_path %>
</p>

app/views/libraries/index.html.erb
<% title "Libraries" %>

<table>
  <tr>
    <th>Project</th>
    <th>Account</th>
    <th>Name</th>
    <th>Global</th>
  </tr>
  <% for library in @libraries %>
    <tr>
      <td><%= library.project_id %></td>
      <td><%= library.account_id %></td>
      <td><%= library.name %></td>
      <td><%= library.global %></td>
      <td><%= link_to "Show", library %></td>
      <td><%= link_to "Edit", edit_library_path(library) %></td>
      <td><%= link_to "Destroy", library, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Library", new_library_path %></p>

app/views/libraries/new.html.erb
<% title "New Library" %>

<%= render 'form' %>

<p><%= link_to "Back to List", libraries_path %></p>

app/views/libraries/show.html.erb
<% title "Library" %>

<p>
  <strong>Project:</strong>
  <%= @library.project_id %>
</p>
<p>
  <strong>Account:</strong>
  <%= @library.account_id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @library.name %>
</p>
<p>
  <strong>Global:</strong>
  <%= @library.global %>
</p>

<p>
  <%= link_to "Edit", edit_library_path(@library) %> |
  <%= link_to "Destroy", @library, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", libraries_path %>
</p>

app/views/pages/_form.html.erb
<%= form_for new_project_page_path do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :markup %><br />
    <%= f.text_area :markup %>
  </p>
  <p>
    <%= f.label :styles %><br />
    <%= f.text_area :styles %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/pages/edit.html.erb
<% title "Edit Page" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @page %> |
  <%= link_to "View All", pages_path %>
</p>

app/views/pages/index.html.erb
<% title "Pages" %>

<table>
  <tr>
    <th>Project</th>
    <th>Name</th>
    <th>Markup</th>
    <th>Styles</th>
  </tr>
  <% for page in @pages %>
    <tr>
      <td><%= page.project_id %></td>
      <td><%= page.name %></td>
      <td><%= page.markup %></td>
      <td><%= page.styles %></td>
      <td><%= link_to "Show", page %></td>
      <td><%= link_to "Edit", edit_page_path(page) %></td>
      <td><%= link_to "Destroy", page, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Page", new_page_path %></p>

app/views/pages/new.html.erb
<% title "New Page" %>

<%= render 'form' %>

<p><%= link_to "Back to List", project_pages_path %></p>

app/views/pages/show.html.erb
<% title "Page" %>

<p>
  <strong>Project:</strong>
  <%= @page.project_id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @page.name %>
</p>
<p>
  <strong>Markup:</strong>
  <%= @page.markup %>
</p>
<p>
  <strong>Styles:</strong>
  <%= @page.styles %>
</p>

<p>
  <%= link_to "Edit", edit_page_path(@page) %> |
  <%= link_to "Destroy", @page, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", pages_path %>
</p>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :overview %><br />
    <%= f.text_area :overview %>
  </p>
  <p>
    <%= f.label :announcement %><br />
    <%= f.text_area :announcement %>
  </p>
  <p>
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/_library.html.haml
#library
  %hgroup  
    library

  // headings
  .item
    %h1 heading 1
  .item
    %h2 heading 2
  .item
    %h3 heading 3
  .item
    %h4 heading 4
  .item
    %h5 heading 5
  .item
    %h6 heading 6                    

  // lists
  .item
    %ul.horizontal
      %li one
      %li two
      %li three
  .item
    %ul
      %li one
      %li two
      %li three
  .item
    %ol
      %li one
      %li two
      %li three

  // text
  .item
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    

app/views/projects/_panels.html.haml
.panels
  

app/views/projects/_toolbar.html.haml
#toolbar
  .columns
    %span.number X 
    %span.label columns
    = link_to "-", void_path
    = link_to "+", void_path

  

app/views/projects/edit.html.haml
- content_for :page_title do
  %h1.page edit project
//

= render "form"

app/views/projects/index.html.haml
- content_for :title do
  %h1.page
    projects
    %span 
      = raw("(#{link_to('new', new_project_path)})")
//

%table
  %thead
    %tr
      %th Name
      %th Overview
      %th Announcement
      %th Status
      %th{:colspan => 3}
  %tbody
    - for project in @projects
      %tr
        %td= project.name
        %td= project.overview
        %td= project.announcement
        %td= project.status
        %td= link_to "show", project
        %td= link_to "edit", edit_project_path(project)
        %td= link_to "destroy", project, :confirm => 'Are you sure?', :method => :delete
  

app/views/projects/new.html.haml
- content_for :page_title do
  %h1.page new project
//

= render "form"

app/views/projects/show.html.haml
#canvas
  .column

- content_for :modal do
  = render "toolbar"
  = render "library"
//

  